---
title: "Benchmarks"
author: "Johan Larsson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmarks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(ggplot2)
library(tidyr)
theme_set(theme_bw())
```

## Benchmarks

In this vignette, we will provide a matrix of benchmarks for the
solvers, penalties, and GLM families in **golem**.

First, we setup a function to plot the results from the fit.

```{r}
set.seed(1)

library(golem)

plot_optim <- function(fit) {
  d <- attr(fit, "diagnostics")
  y <- d$loss
  
  rel_change <- diff(y)/y[-length(y)]
  
  trunc_ind <- which(abs(rel_change) < 1e-5)[1]
  
  trunc_ind <- ifelse(is.na(trunc_ind), length(y), trunc_ind)
  
  Suboptimality <- y[1:trunc_ind] - min(y)
  Time <- d$time[1:trunc_ind]
  
  data.frame(Suboptimality = Suboptimality, Time = Time) %>%
    ggplot(aes(x = Suboptimality, y = Time)) +
    geom_line() +
    xlab("Time (seconds)")
}
```

### Gaussian model

```{r, fig.cap = "Objective loss over time for the abalone data set (Gaussian response)."}
x <- as.matrix(abalone$x)
y <- abalone$y

fit <- golem(x, y, family = "gaussian",
             solver = fista,
             diagnostics = TRUE)
plot_optim(fit)
```

### Binomial model

```{r, fig.cap = "Objective loss over time for the heart data set (binomial response)."}
x <- as.matrix(heart$x)
y <- heart$y

fit <- golem(x, y, family = "binomial",
             solver = fista,
             diagnostics = TRUE)

plot_optim(fit)
```


