// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// golemDense
Rcpp::List golemDense(arma::mat X, arma::vec y, const Rcpp::List control);
RcppExport SEXP _golem_golemDense(SEXP XSEXP, SEXP ySEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(golemDense(X, y, control));
    return rcpp_result_gen;
END_RCPP
}
// prox_slope_cpp
arma::vec prox_slope_cpp(const arma::vec& y, const Rcpp::List& args);
RcppExport SEXP _golem_prox_slope_cpp(SEXP ySEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_slope_cpp(y, args));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_golem_golemDense", (DL_FUNC) &_golem_golemDense, 3},
    {"_golem_prox_slope_cpp", (DL_FUNC) &_golem_prox_slope_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_golem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
