# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

golemDense <- function(X, y, control) {
    .Call(`_golem_golemDense`, X, y, control)
}

prox_slope_cpp <- function(y, lambda) {
    .Call(`_golem_prox_slope_cpp`, y, lambda)
}

