# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

golemDense <- function(x, y, control) {
    .Call(`_golem_golemDense`, x, y, control)
}

prox_slope_cpp <- function(y, args) {
    .Call(`_golem_prox_slope_cpp`, y, args)
}

colNorms <- function(x, norm_type = 2L) {
    .Call(`_golem_colNorms`, x, norm_type)
}

rowNorms <- function(x, norm_type = 2L) {
    .Call(`_golem_rowNorms`, x, norm_type)
}

